name: 🧨 Destruir infraestructura AWS

on:
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: 'Infra cleanup'
        description: 'Release notes o motivo de la destrucción'

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Clonar repositorio
        uses: actions/checkout@v4

      - name: 🔐 Guardar clave SSH privada (opcional, por si queda la instancia colgando)
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa

      - name: ⚙️ Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.0

      - name: 🔐 Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: 📄 Crear archivo de variables para Terraform
        run: |
          echo 'public_key = "${{ secrets.PUBLIC_KEY }}"' > terraform.auto.tfvars

      - name: 📦 Inicializar Terraform
        run: terraform init

      - name: 🔍 Plan de destrucción
        run: terraform plan -destroy

      - name: 💣 Destruir infraestructura
        run: terraform destroy -auto-approve