name: Destruir backend en EC2

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "¿Estás segura que quieres destruir la infraestructura?"
        required: true
        default: "yes"
        type: choice
        options:
          - yes
          - no

jobs:
  destroy:
    if: ${{ github.event.inputs.confirm_destroy == 'yes' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Save SSH Private Key (por si necesitas conectarte antes de destruir)
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create Terraform vars file
        run: |
          echo 'public_key = "${{ secrets.PUBLIC_KEY }}"' > terraform.auto.tfvars

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve